# Generated by Django 4.2.1 on 2023-06-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_url_alter_site_created_at_alter_site_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecookie',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='sites.site', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='SiteAccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succeed', models.BooleanField(default=False, verbose_name='Succeed')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Checked in')),
                ('uploaded', models.FloatField(default=0, verbose_name='Uploaded')),
                ('downloaded', models.FloatField(default=0, verbose_name='Downloaded')),
                ('bonus', models.FloatField(default=0, verbose_name='Bonus')),
                ('active_uploads', models.IntegerField(default=0, verbose_name='Active Uploads')),
                ('active_downloads', models.IntegerField(default=0, verbose_name='Active Downloads')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to='sites.site', verbose_name='Site')),
            ],
        ),
    ]
