name: Build and Push Docker Image


on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Create Docker secrets
        run: |
          echo "${{ secrets.R2_ACCESS_KEY_ID }}" > r2_access_key_id.txt
          echo "${{ secrets.R2_SECRET_ACCESS_KEY }}" > r2_secret_access_key.txt
          echo "${{ secrets.R2_BUCKET_NAME }}" > r2_bucket_name.txt
          echo "${{ secrets.R2_ACCOUNT_ID }}" > r2_account_id.txt

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chrono-walker-bot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/chrono-walker-bot:${{ github.event.release.tag_name }}
          secrets: |
            id=r2_access_key_id,src=r2_access_key_id.txt
            id=r2_secret_access_key,src=r2_secret_access_key.txt
            id=r2_bucket_name,src=r2_bucket_name.txt
            id=r2_account_id,src=r2_account_id.txt
        if: github.event_name == 'release'

      - name: Build and push Docker image (latest only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chrono-walker-bot:latest
          secrets: |
            id=r2_access_key_id,src=r2_access_key_id.txt
            id=r2_secret_access_key,src=r2_secret_access_key.txt
            id=r2_bucket_name,src=r2_bucket_name.txt
            id=r2_account_id,src=r2_account_id.txt
        if: github.event_name != 'release'
